branch-defaults:
<<<<<<< HEAD
  master:
    environment: hacknc20152-env
global:
  application_name: HackNC20152
  default_ec2_keyname: hacknc
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 
  default_region: us-west-2
  profile: eb-cli
  sc: git
