branch-defaults:
  master:
    environment: HackNC2015-dev
global:
  application_name: HackNC2015
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
